"""
Django settings for djangoapi project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
EPSG_FOR_GEOMETRIES=int(os.getenv('EPSG_FOR_GEOMETRIES',4326))
ST_SNAP_PRECISION=float(os.getenv('ST_SNAP_PRECISION',0.0001))
MAX_NUMBER_OF_RETRIEVED_ROWS=int(os.getenv('MAX_NUMBER_OF_RETRIEVED_ROWS',1000))


#use in prod 
#FORCE_SCRIPT_NAME=os.getenv('FORCE_SCRIPT_NAME')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY','DKLSJGHFHF654165464kasdjhadkgf')

# SECURITY WARNING: don't run with debug turned on in production!
REMOTE_DEBUG = False
#DEBUG= False
DEBUG = os.getenv("DEBUG", 'False').lower() in ('true', '1', 't')

#use in dev
ALLOWED_HOSTS = [os.getenv('DJANGO_ALLOWED_HOSTS')]

#------------------ use in prod --------------------------------------------
#allowed_hosts_str = os.getenv('DJANGO_ALLOWED_HOSTS')
#if allowed_hosts_str:
#    # Si la variable de entorno es el comodín, asigna la lista con el comodín
#    if allowed_hosts_str == '*':
#        ALLOWED_HOSTS = ['*']
#    else:
#        # Si son hosts específicos, los separa y limpia
#        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
#else:
#    # Si la variable no existe, asigna una lista vacía para seguridad
#    ALLOWED_HOSTS = []
#

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #required by geodjango
    'django.contrib.gis',
    #para el CORS
    'corsheaders',
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
    'drf_yasg',
    #add all your django apps here
    'core',
    'FELA'
]

# MODELO DE USUARIO CUSTOM
AUTH_USER_MODEL = 'core.CustomUser'

# MIDDLEWARE

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#para el CORS
if DEBUG:
    #CORS_ALLOW_ALL_ORIGINS = True   <-- Not allowed any more for chrome
    #You need to specify the allowed origins
    CORS_ALLOWED_ORIGINS=['http://localhost:5173', "http://localhost:3000", 'http://localhost:8888', 'https://nominatim.openstreetmap.org']

#necressary to allow the cookies to be sent in the header of the request
CORS_ALLOW_CREDENTIALS = True

# CSRF
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8080",
    "http://localhost:4200",
    "http://localhost:5173",
    "https://nominatim.openstreetmap.org",
    'https://gisserver.car.upv.es'
]

# Configuración para que JS pueda leer el token
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

ROOT_URLCONF = 'djangoapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['core'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        #ENGINE': 'django.db.backends.postgresql_psycopg2',
        #required by geodjango
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
        'OPTIONS': {
            'options': '-c search_path=eventos,public',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# SESIONES
# ============================================
SESSION_COOKIE_AGE = 3600 #1 hour 
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = False



# Memoria 
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'eventos-cache',
        'TIMEOUT': 60 * 60 * 24 * 7,
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


#use in dev
STATIC_URL = 'static/'

# --------------------------use in prod ------------------------------

#STATIC_URL = os.getenv('DJANGO_STATIC_URL')
#MEDIA_URL = 'media/'
#
##STATIC_ROOT = '/usr/src/static_root'
#STATIC_ROOT = BASE_DIR / 'static_root'
#MEDIA_ROOT = BASE_DIR / 'media_root'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    # Autenticación por sesión
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Permisos por defecto (lectura pública)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # Paginación
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # Filtros
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Formato de fecha
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    # Manejo de excepciones
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# CONFIGURACIÓN DE EMAIL

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS','True').lower() == 'true' #Devuelve True si se cumple
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_UPV = os.getenv('EMAIL_UPV')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_FROM = os.getenv('EMAIL_FROM')

# Administradores que recibirán emails de notificación
ADMINS=[('Gaspar Mora', 'joamona@cgf.upv.es')]


# En desarrollo, guardar emails en archivos en lugar de enviarlos
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = BASE_DIR / "sent_emails"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

#use in prod
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"